// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_96r3aYykIr8i2ZrKTd9UzsqV-FjMK6g',
    appId: '1:1088642855812:web:82ca2bca73141e40ca63d1',
    messagingSenderId: '1088642855812',
    projectId: 'lua-cydeva',
    authDomain: 'lua-cydeva.firebaseapp.com',
    storageBucket: 'lua-cydeva.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDcgGfnXvesXiJd_TPS-8yjfm0Yiq8UsQ',
    appId: '1:1088642855812:android:4d628dd36a8c7b61ca63d1',
    messagingSenderId: '1088642855812',
    projectId: 'lua-cydeva',
    storageBucket: 'lua-cydeva.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-sz40e1lpmygb1uQjqJA025JGnJJxGKI',
    appId: '1:1088642855812:ios:bab0b92e95570013ca63d1',
    messagingSenderId: '1088642855812',
    projectId: 'lua-cydeva',
    storageBucket: 'lua-cydeva.appspot.com',
    androidClientId: '1088642855812-0qkjomnqu1353sjg5s7itobi7oeihaeg.apps.googleusercontent.com',
    iosClientId: '1088642855812-cj6c6b90gg559qi18eg3aqk216k6lgit.apps.googleusercontent.com',
    iosBundleId: 'com.example.luaV2Cydeva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-sz40e1lpmygb1uQjqJA025JGnJJxGKI',
    appId: '1:1088642855812:ios:b25a4da0bc132f55ca63d1',
    messagingSenderId: '1088642855812',
    projectId: 'lua-cydeva',
    storageBucket: 'lua-cydeva.appspot.com',
    androidClientId: '1088642855812-0qkjomnqu1353sjg5s7itobi7oeihaeg.apps.googleusercontent.com',
    iosClientId: '1088642855812-flfmci1bg7r1ok5hd7u8dbh028fj6cgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.luaV2Cydeva.RunnerTests',
  );
}
